using Database.NET.Relational.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace NavigationProperties
{
    public class OrderItem
    {
        [Key]
        [AutoGenerated]
        public int OrderItemId { get; set; }

        //This is the foreign key to the order
        public int Order_Id { get; set; } 

        //This is the foreign key to the item
        public int Item_Id { get; set; }

        public int Quantity { get; set; }

        [Relationship("Order_Id", "OrderId")]
        public virtual Order Order { get; set; }

        [Relationship("Item_Id", "ItemId")]
        public virtual Item Item { get; set; }
    }
}
