using Database.NET.Relational;
using Database.NET.Relational.Attributes;
using System;
using System.Collections.Generic;
using System.Text;

namespace Migrations
{
    public class Order
    {
        [Key]
        [AutoGenerated]
        public int OrderId { get; set; }

        [Size(50)]
        public string CustomerName { get; set; }

        public int OrderNumber { get; set; }

        //The NavigationCollection attributes tells Database.Net
        //what property to look at on the related(OrderItems) table to find
        //the relationship
        [NavigationCollection("Order")]
        public virtual NavigationCollection<OrderItem> OrderItems { get; set; }
    }
}
